### ISSUE TITLE
Add overwrite in statefulset for peering address

### ISSUE THREAD

**Issue by rilyw** [akyriako/typesense-operator#2] opened 2024-12-04 16:02 UTC
While deploying Typesense on our cluster we encountered a problem described in this issue on the Typesense github repository.
> https://github.com/typesense/typesense/issues/465

The fix in this [comment](https://github.com/typesense/typesense/issues/465#issuecomment-1727704144) eliminates the problem, but we can not add it to the configuration of the custom resource, since the crd and statefulset don't allow any argument to change the peering address. 
The only working solution at the moment is to install the helm chart and then add this:
``` yaml
- name: TYPESENSE_PEERING_ADDRESS
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.podIP
```
to the running statefulset. For the deployment we would like to just install the helm chart and not make any changes to the running system.

A solution could look something like this:

Add a variable named "TYPESENSE_PEERING_ADDRESS" to the Env property of the statefulset [here](https://github.com/akyriako/typesense-operator/blob/57e20b81ce45aa595a10d6c3d03e72933381f034/internal/controller/typesensecluster_statefulset.go#L92).

**Comment by akyriako** [comment] 2024-12-05 07:21
Hi @rilyw, this operator has been developed to explicitly solve the exact problem described in this issue https://github.com/typesense/typesense/issues/465, and it does; check [Problem 1](https://github.com/akyriako/typesense-operator?tab=readme-ov-file#problem-1-quorum-reconfiguration) & [Problem 2](https://github.com/akyriako/typesense-operator?tab=readme-ov-file#problem-2-recovering-a-cluster-that-has-lost-quorum) analysis in the README.md. By just changing the peering port **will not** solve you the problems arousing when pods leave or join the cluster!

Nevertheless the operator is still in beta phase; heavily tested and gathering feedback (thank you very much both for the interest and opening this issue). Graduating to a production-ready state is expected by end of January. As a matter of fact, lots of staff must be added in the (re)configuration of the `TypesenseCluster` CRD (like tolerations, node selector and as you mentioned custom API and Peering ports among others).

Your requested changes are valid and will be incorporated soon, latest till end of next week you will be able to test them.

Cheers!

**Comment by akyriako** [comment] 2024-12-05 07:41
Hi @rilyw, I think I jumped **too** fast answering you back (maybe it's still early in my TZ and I urgently need more coffee I guess). The user-defined API and Peering ports **are already implemented and tested**. Check the specs of the `TypesenseCluster` CRD [here](https://github.com/akyriako/typesense-operator/blob/57e20b81ce45aa595a10d6c3d03e72933381f034/api/v1alpha1/typesensecluster_types.go#L38). The explanation about https://github.com/typesense/typesense/issues/465 stays as it is. What you need to do, in order to provision a cluster with user-defined ports, is to **change** the manifest you used to install a `TypesenseCluster` CR by adding an `apiPort` and a `peeringPort` (they default to `8108` & `8107` respectively and if you don't provide an explicit value they are just omitted from the yaml manifest by design):

```yaml
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster-1
spec:
  image: typesense/typesense:27.1
  apiPort: 28108
  peeringPort: 28107
  replicas: 3
  storage:
    size: 10Mi
    storageClassName: csi-disk
```

The values `28108` & `28107` are just for the sake of the example, defined whatever fits your scenario.

**Comment by rilyw** [comment] 2024-12-05 12:18
Thanks for the quick answer.
You are correct, changing the peering and api port is already possible and also that changing them wouldn't solve our problem, but we would like to change the peering **address** not the **port**.

Our specific problem is that on the initial start of the cluster with 3 replicas, that the pods don't find each other and they cannot elect a leader. The controller then goes the right path of problem 2, all nodes fail their health check since they are trying to find each other and themselves. There are no problems with memory or the disk and the operator downsizes Typesense from 3 to 1 pod. This pod is still unhealthy and can not elect itself as leader, as it still can not find itself in the group. The node never gets upsized to the desired 3 replicas.

Setting the peering **address** on start eliminates this problem and after startup the operator takes over.

**Comment by akyriako** [comment] 2024-12-05 13:39
Now I got it. 

Firstly, about setting `TYPESENSE_PEERING_ADDRESS`; I am not sure how this is going to help the situation because eventually your `Pod` IP will somewhen change and then you will need to restart the `Pod` anyway to get the new environment variable. That's why the whole concept of this controller is to **force** raft, one way or another, to take the peering addresses strictly from the `ConfigMap`, and these peering addresses should be only the FQDN of the endpoints of the headless service so it works completely independently from Pod IPs volatility.

Secondly, I am a bit surprised with that:

> There are no problems with memory or the disk and the operator downsizes Typesense from 3 to 1 pod. This pod is still unhealthy and can not elect itself as leader, as it still can not find itself in the group. The node never gets upsized to the desired 3 replicas.

because the whole thing/promise/guarantee of this controller (based on the recommendations of typesense themselves as to kill all the Pods in order to rebuild the quorum) is that by scaling the `StatefulSet` down to 1 replica it will then let raft elect the leader easily. I have extensively tested the controller and I haven't ever seen it failing to recover a single instance cluster so far. And the keyword here is "so far", that's why I would like to know the frame conditions of your cluster so I can debug the issue further. For that matter I have two questions/requests:

1. **Can you please share the logs of the pod of the single instance cluster?** (if you cannot share them in public here, you can send them to my email address)
2. **Can you please tell me what is the amount of data you are having in the cluster?** I do have tested hundreds of clusters with the controller in low volume scenarios, **but not yet** in high volume ones, and I have a suspicion that there might be the problem. That raft doesn't have enough time to do the log replication (due to the big volume of data) and then elect a leader and declare itself healthy (in the single instance cluster all that).

Anyways thanks for finding this corner case!

**Comment by rilyw** [comment] 2024-12-05 15:49
1. Here the logs of the one replica that is running after getting reset.
> kubectl logs -n typesense pods/cluster-sts-0
I20241204 14:01:23.391173     1 typesense_server_utils.cpp:346] Starting Typesense 27.1
I20241204 14:01:23.391206     1 typesense_server_utils.cpp:349] Typesense is using jemalloc.
I20241204 14:01:23.391575     1 typesense_server_utils.cpp:411] Thread pool size: 48
I20241204 14:01:23.400264     1 store.cpp:40] Initializing DB by opening state dir: /usr/share/typesense/data/db
I20241204 14:01:23.420281     1 store.cpp:40] Initializing DB by opening state dir: /usr/share/typesense/data/meta
I20241204 14:01:23.433122     1 ratelimit_manager.cpp:546] Loaded 0 rate limit rules.
I20241204 14:01:23.433176     1 ratelimit_manager.cpp:547] Loaded 0 rate limit bans.
I20241204 14:01:23.433300     1 typesense_server_utils.cpp:556] Starting API service...
I20241204 14:01:23.433574   214 batched_indexer.cpp:190] Starting batch indexer with 48 threads.
I20241204 14:01:23.433707   216 typesense_server_utils.cpp:499] Conversation garbage collector thread started.
I20241204 14:01:23.433943     1 http_server.cpp:180] Typesense has started listening on port 8108
W20241204 14:01:23.434109   213 typesense_server_utils.cpp:235] Found no matching interfaces, using loopback address as internal IP.
I20241204 14:01:23.436622   214 batched_indexer.cpp:195] BatchedIndexer skip_index: -9999
I20241204 14:01:23.442185   213 server.cpp:1181] Server[braft::RaftStatImpl+braft::FileServiceImpl+braft::RaftServiceImpl+braft::CliServiceImpl] is serving on port=8107.
I20241204 14:01:23.442212   213 server.cpp:1184] Check out http://cluster-sts-0:8107 in web browser.
I20241204 14:01:23.442554   213 raft_server.cpp:69] Nodes configuration: 100.97.234.140:8107:8108
I20241204 14:01:23.442695   213 raft_server.cpp:112] Snapshot does not exist. We will remove db dir and init db fresh.
I20241204 14:01:23.443333   213 store.cpp:246] rm /usr/share/typesense/data/db success
I20241204 14:01:23.443423   213 store.cpp:40] Initializing DB by opening state dir: /usr/share/typesense/data/db
I20241204 14:01:23.452842   213 store.cpp:270] DB open success!
I20241204 14:01:23.452862   213 raft_server.cpp:619] Loading collections from disk...
I20241204 14:01:23.452879   213 collection_manager.cpp:288] CollectionManager::load()
I20241204 14:01:23.452896   213 auth_manager.cpp:35] Indexing 0 API key(s) found on disk.
I20241204 14:01:23.452912   213 collection_manager.cpp:324] Loading upto 24 collections in parallel, 1000 documents at a time.
I20241204 14:01:23.452941   213 collection_manager.cpp:333] Found 0 collection(s) on disk.
I20241204 14:01:23.453895   213 collection_manager.cpp:464] Loaded 0 collection(s).
I20241204 14:01:23.454543   213 raft_server.cpp:626] Finished loading collections from disk.
I20241204 14:01:23.454584   213 raft_server.cpp:637] Loaded 0conversation model(s).
I20241204 14:01:23.454602   213 raft_server.cpp:641] Initializing batched indexer from snapshot state...
I20241204 14:01:23.455391   213 log.cpp:690] Use murmurhash32 as the checksum type of appending entries
I20241204 14:01:23.456323   213 log.cpp:1172] log load_meta /usr/share/typesense/data/state/log/log_meta first_log_index: 1 time: 899
I20241204 14:01:23.457203   213 raft_meta.cpp:521] Loaded single stable meta, path /usr/share/typesense/data/state/meta term 3 votedfor 0.0.0.0:0:0 time: 699
I20241204 14:01:23.457247   213 node.cpp:608] node default_group:127.0.0.1:8107:8108 init, term: 3 last_log_id: (index=0,term=0) conf: 100.97.234.140:8107:8108 old_conf: 
I20241204 14:01:23.457294   213 raft_server.cpp:135] Node last_index: 0
I20241204 14:01:23.457314   213 typesense_server_utils.cpp:296] Typesense peering service is running on 127.0.0.1:8107
I20241204 14:01:23.457326   213 typesense_server_utils.cpp:297] Snapshot interval configured as: 3600s
I20241204 14:01:23.457337   213 typesense_server_utils.cpp:298] Snapshot max byte count configured as: 4194304
W20241204 14:01:23.457350   213 controller.cpp:1550] SIGINT was installed with 1
I20241204 14:01:23.457448   213 raft_server.cpp:706] Term: 3, pending_queue: 0, last_index: 0, committed: 0, known_applied: 0, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 0
W20241204 14:01:23.457468   213 raft_server.cpp:731] Node with no leader. Resetting peers of size: 1
I20241204 14:01:33.458326   213 raft_server.cpp:706] Term: 3, pending_queue: 0, last_index: 0, committed: 0, known_applied: 0, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 0
W20241204 14:01:33.458356   213 raft_server.cpp:731] Node with no leader. Resetting peers of size: 1
I20241204 14:01:33.989699   242 node.cpp:1579] node default_group:127.0.0.1:8107:8108 term 3 start pre_vote
W20241204 14:01:33.989761   242 node.cpp:1589] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.97.234.140:8107:8108
I20241204 14:01:39.035064   242 node.cpp:1579] node default_group:127.0.0.1:8107:8108 term 3 start pre_vote
W20241204 14:01:39.035166   242 node.cpp:1589] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.97.234.140:8107:8108
I20241204 14:01:43.459349   213 raft_server.cpp:706] Term: 3, pending_queue: 0, last_index: 0, committed: 0, known_applied: 0, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 0
W20241204 14:01:43.459388   213 raft_server.cpp:731] Node with no leader. Resetting peers of size: 1
I20241204 14:01:45.024345   242 node.cpp:1579] node default_group:127.0.0.1:8107:8108 term 3 start pre_vote
W20241204 14:01:45.024400   242 node.cpp:1589] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.97.234.140:8107:8108
I20241204 14:01:50.675556   242 node.cpp:1579] node default_group:127.0.0.1:8107:8108 term 3 start pre_vote
W20241204 14:01:50.675606   242 node.cpp:1589] node default_group:127.0.0.1:8107:8108 can't do pre_vote as it is not in 100.97.234.140:8107:8108
I20241204 14:01:53.461045   213 raft_server.cpp:706] Term: 3, pending_queue: 0, last_index: 0, committed: 0, known_applied: 0, applying: 0, pending_writes: 0, queued_writes: 0, local_sequence: 0

As you can see here
> 213 typesense_server_utils.cpp:296] Typesense peering service is running on 127.0.0.1:8107

the first peering address is localhost instead of something that is written in the configMap. If we set this to the pod IP itself it can firstly find itself and then also the other pods. 

2. We are deploying it on a cluster where nothing other than normal networking and other infrastructure pods are running, since we first want to test Typesense in a cluster before deploying it in production.

**Comment by mleklund** [comment] 2024-12-05 16:18
I am going to wade in a bit and add my 2 cents as I have taken the same route as @akyriako and written my own operator as I had found the existing python operator did not fit my needs.  The operator I have written, which is private at the moment, I noticed when I used dns names in the configmap and we had some sort of failover situation, that it took the raft a while to figure things out.  The combination of switching the configmap to IP addresses, forcing configmap updates internally in the pod via an annotation, and setting the peering address via an environment variable for the pod IP that I was able to significantly speed up the raft failover.

I am very interested in the project as I really like some of the ways things have been handled vs how I handled them in my own. I have also implemented snapshotting and restoring in my own version if there is sufficient interest.

**Comment by akyriako** [comment] 2024-12-06 07:36
Hi @rilyw  
> I20241204 14:01:23.457314 213 typesense_server_utils.cpp:296] Typesense peering service is running on 127.0.0.1:8107

that is **extremely** interesting and I need to reproduce it in order to investigate it. I created a brand new typesense cluster (no data or metadata left-overs to load from in-memory sets or PVs), on a brand new Kubernetes cluster (Managed K8S on our public cloud) and the 3-node typesense cluster needed around 50sec to elect a leader without any complications. 

These are the logs I got out (and they make the thing even more surprising to me)

![image](https://github.com/user-attachments/assets/227e3378-7742-430a-bc6f-b86f2fe67c18)

First observations @rilyw @mleklund 

1. First, **the typesense is listening to the Pod IP and not to the loopback address**, without an additional envVar that retrieves the Pod IP and without adding IPs instead of FQDN in the ConfigMap. The Pod IPs are resolved "organically" if I could use that term but you know what I mean. (and that exactly was the very purpose I started building this controller, to avoid the sidecar and the ugliness/uncertainty of having to dig up the Pod IPs -- which in certain time-windows might not even be ready or available yet). With FQDNs you need to worry for none of those (I will stick to FQDNs till I am proven wrong or idiot or why not both :laughing: )
2. Second, **raft is picking up the data of ConfigMap and then resolves the IPs** (check out the logs; the raft configuration is made out of Pod IPs) 
3. Third, **the StatefulSet didn't need to scale down** in the first run, it elected a leader in ~50sec.

@rilyw this doesn't mean I dismiss the behavior you presented, actually the contrary; I need urgently to reproduce it so I understand it. For that matter, I will check again under multiple frame conditions combinations (KIND, bare metal clusters, managed k8s in Azure and AWS) to figure when and mostly why that happens. 

@mleklund thanks for taking an interest in this project. I have more than "_sufficient interest_" to listen to new ideas and feature requests or even to contributions!

**Comment by DevPhilB** [comment] 2024-12-06 09:37
Hi @akyriako,

thank you for your commitment and to check more clusters.
On a local minikube, it was no problem for us.
But it seems to concern more (external) clusters, as @wille had the same problem (without this operator) and luckily found the solution with the Peering Address.

**Comment by akyriako** [comment] 2024-12-07 07:46
Hi @rilyw @DevPhilB 

I tested multiple times on various cloud providers (AWS, Azure, Open Telekom Cloud)  and on bare metal and (un)fortunately I didn't manage to reproduce the issue. Wherever I tested typesense was listening to the correct IP and not to the loopback one. Nevertheless, I added `TYPESENSE_PEERING_ADDRESS` as an EnvVar as was discussed so we can cross-examine the behaviour in your environment:
```
{
       Name: "TYPESENSE_PEERING_ADDRESS",
       ValueFrom: &corev1.EnvVarSource{
	FieldRef: &corev1.ObjectFieldSelector{
		FieldPath: "status.podIP",
	}},
},
```
https://github.com/akyriako/typesense-operator/blob/5b63fcca43d810210fd05e3ca6303c79aa58f59d/internal/controller/typesensecluster_statefulset.go#L121

Update the helm chart to the new version 0.2.0 and give it a go (I'd suggest trying it on new clusters and not on existing ones)

**Closed** 2024-12-10 10:08 UTC
Labels: enhancement
